# Ansible playbook to setup NVidia drivers
# Last update: 2021.11.24 17.33
- hosts: all
  tags: nvidia
  become: yes

  tasks:
    - name: Detect NVidia devices
      command: ubuntu-drivers devices

    - name: Install recommended NVidia graphics driver
      command: ubuntu-drivers autoinstall

    - name: Install NVidia Optimus GPU switcher
      apt:
        name: mate-optimus
        state: latest

    - name: Fix Nvidia blacklist conf
      command: sed -i -r 's/^(alias nvidia off)/#\1/' /lib/modprobe.d/blacklist-nvidia.conf

    - name: Reboot
      reboot:
