# Ansible playbook to setup NVidia drivers
# Last update: 2021.11.24 17.33
- hosts: all
  tags: nvidia
  become: yes

  tasks:
    - name: Detect NVidia devices
      command: ubuntu-drivers devices

    - name: Install recommended NVidia graphics driver
      become: yes
      command: ubuntu-drivers autoinstall

    - name: Reboot
      become: yes
      reboot:
