# Ansible playbook to setup my workstation
# Last update: 2021.11.22 17.33
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
      changed_when: no

    - name: Create temp dir
      file:
        path: "{{ tmp_dir }}"
        state: present

  tasks:
    # setup users
    # - include: users/ansible.yml

    - name: Include default packages
      include_tasks: packages/apt.yml
      tags: default

    - name: Include LibreOffice installation
      include_tasks: packages/libreoffice.yml
      tags: libreoffice

    - name: Include Browser installation
      include_tasks: packages/browser.yml
      tags: browsers

    - name: Include default development softwares installation
      include_tasks: packages/development.yml
      tags: development

    - name: Include LocalWP installation
      include_tasks: packages/localwp.yml
      tags: localwp


# Clean Up
- hosts: all
  become: yes
  tasks:
    - name: Cleanup cache
      apt:
        autoclean: yes
      changed_when: no

    - name: Autoremove orphan packages
      apt:
        autoremove: yes
        purge: yes
      changed_when: no
