# Ansible playbook to setup my workstation
# Last update: 2021.11.22 17.33
- hosts: all
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: "Update apt cache"
      apt: update_cache=yes
      changed_when: false

    - name: "Create temp dir"
      file:
        path: "{{ tmp_dir }}"
        state: present

  tasks:
    # setup users
    # - include: users/ansible.yml

    # install packages
    - include: packages/apt.yml
    - include: packages/libreoffice.yml


# Clean Up
- hosts: all
  become: true
  tasks:
    - name: "Cleanup cache"
      apt:
        autoclean: true
      changed_when: false

    - name: "Autoremove orphan packages"
      apt:
        autoremove: true
        purge: true
      changed_when: false
