# Ansible playbook to setup my workstation
# Last update: 2021.11.22 17.33
- hosts: all
  become: true

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes
      changed_when: false

  tasks:
    # setup users
    # - include: users/ansible.yml

    # install packages
    - include: packages/apt.yml
    - include: packages/libreoffice.yml


# Clean Up
- hosts: all
  become: true
  tasks:
    - name: cleanup cache
      apt:
        autoclean: true
      changed_when: false

    - name: autoremove orphan packages
      apt:
        autoremove: true
        purge: true
      changed_when: false
