# Ansible playbook to setup my workstation
# Last update: 2021.11.22 17.33
- hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
      changed_when: no

  roles:
    - role: default
      ignore_errors: true
    - role: security
      ignore_errors: true
    - role: office
      ignore_errors: true
    - role: communicators
      ignore_errors: true
    - role: job
      ignore_errors: true
    - role: development
      ignore_errors: true
    - role: support
      ignore_errors: true
    - role: android
      ignore_errors: true
    - role: games
      ignore_errors: true
    - role: entertainment
      ignore_errors: true


  # Clean Up
  post_tasks:
    - name: Cleanup cache
      become: yes
      apt:
        autoclean: yes
      changed_when: no

    - name: Autoremove orphan packages
      become: yes
      apt:
        autoremove: yes
        purge: yes
      changed_when: no
