# Ansible playbook to setup my workstation
# Last update: 2021.11.22 17.33
- hosts: localhost
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache
      become: yes
      apt: 
        update_cache: yes
      changed_when: no

    - name: Create temp dir
      tags: always
      file:
        path: "{{ tmp_dir }}"
        state: directory
      check_mode: no

  tasks:
    # setup users
    # - include: users/ansible.yml

    - name: Include default packages and configurations
      include_tasks: packages/base.yml
      tags: 
        - default
        - base
        - dotfiles
        - ssh

    - name: Include Snap Upgrade
      include_tasks: packages/snap.yml
      tags: snap

    - name: Include Zsh configuration
      include_tasks: packages/ohmyzsh.yml
      tags: zsh

    - name: Install Browsers
      include_tasks: packages/download_and_install_apt_package.yml
      tags: "{{ package.tags }}"
      vars:
        package:
          name: Vivaldi Browser
          tags: browser
          url: "{{ vivaldi_browser_url }}"

    - name: Install Authy
      include_tasks: packages/install_snap_package.yml
      tags: "{{ package.tags }}"
      vars:
        package:
          name: Authy
          tags: authy
          id: authy

    - name: Include Autokey installation
      include_tasks: packages/autokey.yml
      tags: autokey

    - name: Install Discord
      include_tasks: packages/download_and_install_apt_package.yml
      tags: "{{ package.tags }}"
      vars:
        package:
          name: Discord
          tags: discord
          url: "{{ discord_url }}"

    - name: Include Telegram installation
      include_tasks: packages/telegram.yml
      tags: telegram

    - name: Include NeoVim installation
      include_tasks: packages/vim.yml
      tags:
        - vim
        - neovim

    - name: Include Tmate and Tmux installation
      include_tasks: packages/tmux.yml
      tags:
        - tmux
        - tmate

    - name: Include VSCode installation
      include_tasks: packages/vscode.yml
      tags: vscode

    - name: Include Java and JDK configuration
      include_tasks: packages/java.yml
      tags: java

    - name: Include Python instalation 
      include_tasks: packages/python.yml
      tags: python

    - name: Install LocalWP
      include_tasks: packages/download_and_install_apt_package.yml
      tags: "{{ package.tags }}"
      vars:
        package:
          name: LocalWP
          tags: localwp
          url: "{{ localwp_url }}"

    - name: Install Anbox
      include_tasks: packages/anbox.yml
      tags: "{{ package.tags }}"
      vars:
        package:
          name: Anbox (Android in a Box)
          tags: anbox
          id: anbox

    - name: Include Calibre installation
      include_tasks: packages/calibre.yml
      tags: calibre

    - name: Install LibreOffice
      include_tasks: packages/install_apt_package.yml
      tags: "{{ package.tags }}"
      vars:
        package:
          name: LibreOffice Oficial
          tags: libreoffice
          id: libreoffice
          apt_repo: "ppa:libreoffice/ppa"


    - name: Include games platforms installation
      include_tasks: packages/games.yml
      tags:
        - games
        - gog
        - epic
        - steam



  # Clean Up
  post_tasks:
    - name: Cleanup cache
      become: yes
      apt:
        autoclean: yes
      changed_when: no

    - name: Autoremove orphan packages
      become: yes
      apt:
        autoremove: yes
        purge: yes
      changed_when: no

    - name: Remove temp dir
      tags: always
      file:
        path: "{{ tmp_dir }}"
        state: absent
      check_mode: no
