# Ansible playbook to setup my workstation
# Last update: 2021.11.22 17.33
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
      changed_when: no

    - name: Create temp dir
      file:
        path: "{{ tmp_dir }}"
        state: present

  tasks:
    # setup users
    # - include: users/ansible.yml

    - name: Include default packages
      include_tasks: packages/apt.yml
      tags: default

    - name: Include Snap Upgrade
      include_tasks: packages/snap.yml
      tags: snap

    - name: Include Zsh configuration
      include_tasks: packages/ohmyzsh.yml
      tags: zsh

    - name: Include Browser installation
      include_tasks: packages/browser.yml
      tags: browsers

    - name: Include Authy installation
      include_tasks: packages/authy.yml
      tags: authy

    - name: Include Autokey installation
      include_tasks: packages/autokey.yml
      tags: autokey

    - name: Include Discord installation
      include_tasks: packages/discord.yml
      tags: discord

    - name: Include default development softwares installation
      include_tasks: packages/development.yml
      tags: development

    - name: Include LocalWP installation
      include_tasks: packages/localwp.yml
      tags: localwp

    - name: Include Anbox installation
      include_tasks: packages/anbox.yml
      tags: anbox

    - name: Include LibreOffice installation
      include_tasks: packages/libreoffice.yml
      tags: libreoffice


# Clean Up
- hosts: all
  become: yes
  tasks:
    - name: Cleanup cache
      apt:
        autoclean: yes
      changed_when: no

    - name: Autoremove orphan packages
      apt:
        autoremove: yes
        purge: yes
      changed_when: no
