# Ansible playbook to setup my workstation
# Last update: 2021.11.22 17.33
- hosts: localhost
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache
      become: yes
      apt: 
        update_cache: yes
      changed_when: no

  roles:
    - default
    - office
    - communicators
    - job
    - development
    - support
    - android
    - games


  # Clean Up
  post_tasks:
    - name: Cleanup cache
      become: yes
      apt:
        autoclean: yes
      changed_when: no

    - name: Autoremove orphan packages
      become: yes
      apt:
        autoremove: yes
        purge: yes
      changed_when: no
