calibre_config_dest: "{{ ansible_user_dir }}/Biblioteca do calibre"

obsidian_version: "1.4.13"
obsidian_file: "obsidian_{{ obsidian_version }}_amd64.deb"
obsidian_url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_version }}/{{ obsidian_file }}"
