- name: Install Steam
  tags: 
    - games
    - steam
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags: ["games","steam"]
  vars:
    package:
      name: Steam
      url: "{{ steam_url }}"

- name: Install Epic
  tags: 
    - games
    - epic
  include_role:
    name: common
    tasks_from: download_and_install_package_from_github
    apply:
      tags: ["games","epic"]
  vars:
    package:
      name: Epic Games
      repo: "{{ epic_repo }}"

- name: Install GOG
  tags:
    - games
    - gog
  include_role:
    name: common
    tasks_from: download_and_install_package_from_github
    apply:
      tags: ["games","gog"]
  vars:
    package:
      name: GoG
      tags:
        - games
        - gog
      repo: "{{ gog_repo }}"
