- name: Install Steam
  tags:
    - games
    - steam
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
  vars:
    package:
      name: Steam
      tags: 
        - games
        - steam
      url: "{{ steam_url }}"

- name: Install Epic
  tags: 
    - games
    - epic
  include_role:
    name: common
    tasks_from: download_and_install_package_from_github
  vars:
    package:
      name: Epic Games
      tags:
        - games
        - epic
      repo: "{{ epic_repo }}"

- name: Install GOG
  tags: 
    - games
    - gog
  include_role:
    name: common
    tasks_from: download_and_install_package_from_github
  vars:
    package:
      name: GoG
      tags:
        - games
        - gog
      repo: "{{ gog_repo }}"
