- name: Install Firejail
  tags: 
    - security
    - firejail
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - security
        - firejail
  vars:
    package:
      name: Firejail
      id: "{{ item }}"
      apt_repo: "ppa:deki/firejail"
  with_items:
    - firejail
    - firejail-profiles

- name: Install NordVPN
  tags:
    - security
    - base
    - vpn
  become: yes
  shell: "curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh | bash"


- name: Install Tor Browser
  tags:
    - security
    - tor
  block:
    - name: Download package
      get_url:
        url: "{{ tor_url }}"
        dest: "{{ tmp_dir }}"
      check_mode: no

    - name: Extract package
      unarchive:
        src: "{{ tmp_dir }}/{{ tor_file }}"
        dest: "{{ applications_dir }}"

    - name: Set appropriate permissions
      file:
        path: "{{ tor_dest }}/start-tor-browser.desktop"
        mode: "0750"

    - name: Remove package
      file:
        path: "{{ tmp_dir }}/{{ tor_file }}"
        state: absent
      check_mode: no

