- name: Install Firejail
  tags: 
    - security
    - firejail
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - security
        - firejail
  vars:
    package:
      name: Firejail
      id: firejail

- name: Install NordVPN
  tags:
    - security
    - vpn
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags: 
        - security
        - vpn
  vars:
    package:
      name: NordVPN
      url: "{{ vpn_url }}"

