- name: Install Firejail
  tags: 
    - security
    - firejail
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - security
        - firejail
  vars:
    package:
      name: Firejail
      id: firejail

- name: Install NordVPN
  tags:
    - security
    - base
    - vpn
  block:
    - name: Install Repository
      include_role:
        name: common
        tasks_from: download_and_install_apt_package
        apply:
          tags: 
            - security
            - base
            - vpn
      vars:
        package:
          name: NordVPN Repository
          url: "{{ vpn_url }}"

    - name: Install NordVPN package
      include_role:
        name: common
        tasks_from: install_apt_package
        apply:
          tags:
            - security
            - base
            - vpn
      vars:
        package:
          name: NordVPN package
          id: nordvpn

