- name: Installing and setting up Waydroid
  tags: android
  become: yes
  block:
    - name: Install dependencies
      become: yes
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - curl
          - ca-certificates

    - name: Add official repository
      shell: "curl https://repo.waydro.id | bash"

    - name: Install Waydroid
      include_role:
        name: common
        tasks_from: install_apt_package
        apply:
          tags: android
      vars:
        package:
          name: Waydroid 
          id: waydroid

