- name: Installing and setting up Waydroid
  tags: android
  become: yes
  block:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - curl
          - ca-certificates
          - weston

    - name: Add official repository
      shell: "curl https://repo.waydro.id | bash"

    - name: Install Waydroid
      include_role:
        name: common
        tasks_from: install_apt_package
        apply:
          tags: android
      vars:
        package:
          name: Waydroid 
          id: waydroid

- name: Install Anbox with GAPPS
  tags: anbox
  become: yes
  block:
    - name: Installing Anbox application
      command: snap install --devmode --edge anbox

    - name: Install PreReqs of GAPPS installation
      include_role:
        name: common
        tasks_from: install_apt_package
        apply:
          tags: anbox
      vars:
        package:
          id: "{{ item }}"
          name: "{{ item }}"
      with_items:
        - wget
        - curl
        - lzip
        - tar
        - unzip
        - squashfs-tools

    - name: Installing GAPPS in Anbox
      shell: "curl -s https://raw.githubusercontent.com/geeks-r-us/anbox-playstore-installer/master/install-playstore.sh | bash"
