- name: Install Anbox
  tags: anbox
  include_role:
    name: common
    tasks_from: install_snap_package
    apply:
      tags: anbox
  vars:
    package:
      name: Anbox (Android in a Box)
      id: anbox
      channel: beta

