- name: Install Spotify
  tags:
    - default
    - entertainment
    - spotify
  include_role:
    name: common
    tasks_from: install_snap_package
    apply:
      tags:
        - default
        - entertainment
        - spotify
  vars:
    package:
      id: spotify
