- name: Install Calibre
  tags: 
    - office
    - calibre
    - ebooks
  include_tasks: calibre.yml

- name: Install LibreOffice
  tags: 
    - office
    - libreoffice
  include_role: 
    name: common
    tasks_from: install_apt_package
    apply:
      tags: 
        - office
        - libreoffice
  vars:
    package:
      name: LibreOffice Oficial
      id: libreoffice
      apt_repo: "ppa:libreoffice/ppa"

- name: Install Google Drive folder sync
  tags: 
    - office
    - base
    - gdrive
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags: 
        - office
        - base
        - gdrive
  vars:
    package:
      name: RClone
      id: rclone

- name: Install HTMLDoc
  tags: 
    - office
    - htmldoc
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags: 
        - office
        - htmldoc
  vars:
    package:
      name: HTMLDoc
      id: htmldoc

- name: Install Obsidian
  tags:
    - office
    - base
    - obsidian
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags:
        - office
        - obsidian
  vars:
    package:
      name: Obsidian
      url: "{{ obsidian_url }}"

- name: Install Gimp
  tags:
    - office
    - base
    - gimp
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - office
        - gimp
  vars:
    package:
      name: Gimp
      id: gimp

- name: Install VLC
  tags:
    - office
    - vlc
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - office
        - vlc
  vars:
    package:
      name: VLC
      id: vlc

