- name: Install Calibre
  tags:
    - default
    - office
    - calibre
    - ebooks
    - k2pdf
  include_tasks: calibre.yml

- name: Install LibreOffice
  tags:
    - office
    - libreoffice
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - office
        - libreoffice
  vars:
    package:
      name: LibreOffice Oficial
      id: libreoffice
      apt_repo: "ppa:libreoffice/ppa"

- name: Install Google Drive folder sync
  tags:
    - default
    - office
    - gdrive
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - default
        - office
        - gdrive
  vars:
    package:
      name: RClone
      id: rclone

- name: Install HTMLDoc
  tags:
    - office
    - htmldoc
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - office
        - htmldoc
  vars:
    package:
      name: HTMLDoc
      id: htmldoc

- name: Install Obsidian
  tags:
    - default
    - office
    - obsidian
  include_role:
    name: common
    tasks_from: download_and_install_package_from_github
    apply:
      tags:
        - default
        - office
        - obsidian
  vars:
    package:
      name: Obsidian
      repo: "obsidianmd/obsidian-releases"

- name: Install Gimp
  tags:
    - default
    - office
    - gimp
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - default
        - office
        - gimp
  vars:
    package:
      name: Gimp
      id: gimp

- name: Install VLC
  tags:
    - default
    - office
    - vlc
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - default
        - office
        - vlc
  vars:
    package:
      name: VLC
      id: vlc
