- name: Install Calibre
  tags: 
    - office
    - calibre
    - ebooks
  include_tasks: calibre.yml

- name: Install LibreOffice
  tags: 
    - office
    - libreoffice
  include_role: 
    name: common
    tasks_from: install_apt_package
    apply:
      tags: 
        - office
        - libreoffice
  vars:
    package:
      name: LibreOffice Oficial
      id: libreoffice
      apt_repo: "ppa:libreoffice/ppa"

- name: Install Google Drive folder sync
  tags: 
    - office
    - gdrive
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags: 
        - office
        - gdrive
  vars:
    package:
      name: RClone
      id: rclone

- name: Install HTMLDoc
  tags: 
    - office
    - htmldoc
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags: 
        - office
        - htmldoc
  vars:
    package:
      name: HTMLDoc
      id: htmldoc
