- name: Install Calibre
  tags: calibre
  include_tasks: calibre.yml

- name: Install LibreOffice
  tags: libreoffice
  include_role: 
    name: common
    tasks_from: install_apt_package
    apply:
      tags: libreoffice
  vars:
    package:
      name: LibreOffice Oficial
      id: libreoffice
      apt_repo: "ppa:libreoffice/ppa"

