- name: Install and setup Autokey
  tags: 
      - default
      - autokey
  block:
    - name: Download and install Autokey Common package
      become: yes
      apt: 
        deb: "{{ autokey_common_url }}"

    - name: Download and install Autokey GTK package
      become: yes
      apt: 
        deb: "{{ autokey_gtk_url }}"

    - name: Import configuration files
      git:
        repo: "git@github.com:sidneydemoraes/autokey-config.git"
        dest: "{{ autokey_config_dest }}"
        clone: yes

  ignore_errors: yes
