- name: Install base apt packages
  tags:
    - default
    - base
    - aptbase
  become: yes
  block:
    - name: Add Universe Repository
      apt_repository:
        repo: "{{ item }}"
        state: present
        validate_certs: no
      with_items:
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
        - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe"

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - software-properties-common
        - atop
        - cpulimit
        - curl
        - git
        - htop
        - p7zip-full
        - p7zip-rar
        - screen
        - tar
        - wget
        - gparted
        - bat
        - xclip

- name: Base configurations
  tags:
    - default
    - base
    - dotfiles
  block:
    - name: Copy dot files
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/.{{ item }}"
        force: yes
        mode: 0600
      with_items:
        - "bash_aliases"
        - "bash_exports"
        - "bashrc"
        - "inputrc"
        - "screenrc"
        - "gitconfig"

    - name: Copy DIR_COLORS
      copy:
        src: "DIR_COLORS"
        dest: "{{ ansible_user_dir }}"
        force: yes
        mode: 0600

    - name: Symlink bashrc to bash_profiles
      file:
        src: "{{ ansible_user_dir }}/.bashrc"
        dest: "{{ ansible_user_dir }}/.bash_profile"
        state: link

- name: SSH configuration
  tags:
    - default
    - base
    - ssh
  block:
    - name: Create SSH config directoty
      file:
        path: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: 0700

    - name: Copy SSH config
      copy:
        src: "ssh_config"
        dest: "{{ ansible_user_dir }}/.ssh/config"
        force: yes
        mode: 0600

    - name: Copy SSH keys
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/.ssh"
        mode: 0600
        force: yes
        decrypt: yes
      with_items:
        - id_rsa
        - id_rsa.pub

- name: Upgrade Snap
  become: yes
  tags:
    - default
    - base
    - snap
  apt:
    name: snapd
    state: latest
    only_upgrade: yes

- name: Install 7zip Desktop
  become: yes
  tags:
    - default
    - base
    - 7zip
  snap:
    name: p7zip-desktop
    classic: yes

- name: Install Solaar
  tags:
    - default
    - base
    - solaar
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - default
        - base
        - solaar
  vars:
    package:
      name: Solaar
      apt_repo: "ppa:solaar-unifying/stable"
      id: solaar
