- name: Install and setup basic packages
  tags: 
    - default
    - base
    - dotfiles
    - ssh
    - snap
    - 7zip
  include_tasks: base.yml

- name: Install Slimbook Battery
  tags: slimbook
  include_role:
    name: common
    tasks_from:  install_apt_package
  vars:
    package:
      name: Slimbook Battery
      tags: slimbook
      id: simbookbattery
      apt_repo: "ppa:slimbook/slimbook"

- name: Setup ZSH
  tags: zsh
  include_tasks: ohmyzsh.yml

- name: Install Browsers
  tags: browser
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
  vars:
    package:
      name: Vivaldi Browser
      tags: browser
      url: "{{ vivaldi_browser_url }}"

- name: Install Authy
  tags: authy
  include_role:
    name: common
    tasks_from: install_snap_package
  vars:
    package:
      name: Authy
      tags: authy
      id: authy

- name: Include Autokey installation
  include_tasks: packages/autokey.yml
  tags: autokey
