- name: Install and setup basic packages
  tags: 
    - default
    - base
    - aptbase
    - dotfiles
    - ssh
    - snap
    - 7zip
    - solaar
  include_tasks: base.yml

- name: Install Slimbook Battery
  tags: 
    - default
    - slimbook
  include_role:
    name: common
    tasks_from:  install_apt_package
    apply:
      tags: slimbook
  vars:
    package:
      name: Slimbook Battery
      id: slimbookbattery
      apt_repo: "ppa:slimbook/slimbook"

- name: Setup ZSH
  tags: 
    - default
    - base
    - zsh
  include_tasks: ohmyzsh.yml

- name: Install Browsers
  tags: 
    - default
    - base
    - browser
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags: 
        - default
        - base
        - browser
  vars:
    package:
      name: Vivaldi Browser
      url: "{{ vivaldi_browser_url }}"

- name: Install Authy
  tags: 
    - default
    - base
    - authy
  include_role:
    name: common
    tasks_from: install_snap_package
    apply:
      tags: 
        - default
        - base
        - authy
  vars:
    package:
      name: Authy
      id: authy

- name: Include Autokey installation
  tags: 
    - default
    - autokey
  include_tasks: autokey.yml

- name: Include Wine installation
  tags: 
    - default
    - base
    - wine
  include_tasks: wine.yml

