- name: Installing and Setting up Zsh and Oh My Zsh
  tags: zsh
  block:
  - name: Install Dependencies
    apt:
      name: zsh
      state: latest

  - name: Clone Oh My Zsh
    command:
      cmd: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
      chdir: "{{ ansible_user_dir }}"

  - name: Adjust Oh My Zsh files permissions
    become: yes
    file:
      path: "{{ ansible_user_dir }}/.oh-my-zsh"
      mode: go-w
      recurse: yes

  - name: Set default shell
    become: yes
    user:
      name: "{{ ansible_user_id }}"
      shell: '/bin/zsh'

  - name: Copy zsh configuration file
    copy:
      src: "zshrc"
      dest: "{{ ansible_user_dir }}/.zshrc"
      force: yes

  - name: Copy OhMyZsh configuration file
    copy:
      src: "sid.zsh-theme"
      dest: "~/.oh-my-zsh/themes/"
      force: yes
