- name: Install and setup Wine
  tags: wine
  become: yes
  block:
    - name: Download Wine repository key
      get_url:
        url: "{{ wine_repo_key_url }}"
        dest: "{{ wine_repo_key_dest }}"
      check_mode: no

    - name: Download Wine repository sources
      get_url:
        url: "{{ wine_sources_url }}"
        dest: "{{ wine_sources_dest }}"

    - name: Install Wine
      apt:
        update_cache: yes
        name: winehq-devel
        state: latest
        install_recommends: yes

    - name: Remove outdated version of Winetricks
      apt:
        name: winetricks
        state: absent
        purge: yes

    - name: Download updated Winetricks
      get_url:
        url: "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
        dest: "/usr/bin/local"
        mode: "0754"

    - name: Download Winetricks bash completion
      get_url:
        url: "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks.bash-completion"
        dest: "/usr/share/bash-completion/completions/winetricks"
        force: yes

    - name: Download Winetrics man pages
      get_url:
        url: "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks.1"
        dest: "/usr/share/man/man1"
