- name: Preparing installation and setup of Docker
  tags: docker
  become: yes
  block:
    - name: Uninstalling older versions
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - docker 
          - docker-engine 
          - docker.io 
          - containerd 
          - runc

    - name: Installing pre requisites
      apt:
        name: "{{ packages }}"
        state: latest
        autoclean: yes
      vars:
        packages:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Installing Docker's official GPG key
      rpm_key:
        key: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
        validate_certs: no

    - name: Add Docker's official repository
      apt_repository:
        repo: "https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
