- name: Preparing installation of Java and JDK
  tags:
    - default
    - dev
    - java
  block:
    - name: Installing SDKMan
      shell: "curl -s {{sdkman_url }} | bash executable=/bin/bash"
      ignore_errors: false

    - name: Get latest OpenJDK version
      shell: "source {{ ansible_user_dir }}/.sdkman/bin/sdkman-init.sh && sdk list java | grep -e '-open' | head -1 | awk '{ print $(NF) }'"
      register: openjdk_latest

    - name: "Install OpenJDK version {{ openjdk_latest }}"
      shell: "source {{ ansible_user_dir }}/.sdkman/bin/sdkman-init.sh && sdk install java {{ openjdk_latest }}"

    - name: Setup OpenJDK as default Java version
      shell: "source {{ ansible_user_dir }}/.sdkman/bin/sdkman-init.sh && sdk default java {{ openjdk_latest }}"
