- name: Preparing installation of Java and JDK
  tags:
    - default
    - dev
    - java
  block:
    - name: Installing SDKMan
      shell: "curl -s '{{ sdkman_url }}' | bash"

    - name: Get latest OpenJDK version
      shell: "sdk list java | grep -e '-open' | head -1 | awk '{ print $(NF) }'"
      register: openjdk_latest

    - name: "Install OpenJDK version {{ openjdk_latest }}"
      shell: "sdk install java {{ openjdk_latest }}"

    - name: Setup OpenJDK as default Java version
      shell: "sdk default java {{ openjdk_latest }}"

    - name: Install latest VisualVM version
      shell: "sdk install visualvm"
