- name: Install Vim
  tags:
    - dev
    - base
    - vim
  include_tasks: vim.yml

- name: Install Tmate and Tmux
  tags:
    - dev
    - base
    - tmux
    - tmate
  include_tasks: tmux.yml

- name: Install VSCode
  tags: 
    - dev
    - base
    - vscode
  include_tasks: vscode.yml

- name: Install Java
  tags: 
    - dev
    - java
  include_tasks: java.yml

- name: Install Python
  tags: 
    - dev
    - base
    - python
  include_tasks: python.yml

- name: Install NodeJS
  tags:
    - dev
    - node
  include_tasks: node.yml

- name: Install LocalWP
  tags: 
    - dev
    - localwp
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags: 
        - dev
        - localwp
  vars:
    package:
      name: LocalWP
      url: "{{ localwp_url }}"

- name: Install Docker
  tags: 
    - dev
    - docker
  include_tasks: docker.yml

- name: Install Virtualbox
  tags: 
    - dev
    - virtualbox
  include_tasks: virtualbox.yml

- name: Install GPick
  tags:
    - dev
    - gpick
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - dev
        - gpick
  vars:
    package:
      name: GPick
      id: gpick

