- name: Install NeoVim
  tags:
    - dev
    - vim
    - neovim
  include_tasks: vim.yml

- name: Install Tmate and Tmux
  tags:
    - dev
    - tmux
    - tmate
  include_tasks: tmux.yml

- name: Install Lynx Terminal Browser
  tags:
    - lynx
  include_role:
    name: common
    tasks_from: install_apt_package
    apply:
      tags:
        - lynx
  vars:
    package:
      name: Lynx Browser
      id: lynx

- name: Install VSCode
  tags: 
    - dev
    - vscode
  include_tasks: vscode.yml

- name: Install Java
  tags: 
    - dev
    - java
  include_tasks: java.yml

- name: Install Python
  tags: 
    - dev
    - python
  include_tasks: python.yml

- name: Install LocalWP
  tags: 
    - dev
    - localwp
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags: 
        - dev
        - localwp
  vars:
    package:
      name: LocalWP
      url: "{{ localwp_url }}"

- name: Install Docker
  tags: 
    - dev
    - docker
  include_tasks: docker.yml

- name: Install Virtualbox
  tags: 
    - dev
    - virtualbox
  include_tasks: virtualbox.yml

