- name: Install and setup Tmux and Tmate
  tags:
    - dev
    - tmux
    - tmate
  block:
    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - tmux
          - tmate

    - name: Copy tmux configuration file
      copy:
        src: "tmux.conf"
        dest: "{{ ansible_user_dir }}/.tmux.conf"
        mode: '664'

    - name: Install plugin manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
