- name: Install and setup Vim
  tags:
    - default
    - dev
    - vim
  block:
    - name: Install package
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim
        - vim_gtk

    - name: Copy configuration file
      copy:
        src: 'vimrc'
        dest: "{{ ansible_user_dir }}/.vimrc"
        force: yes
