- name: Install and setup Vim
  tags: 
    - dev
    - vim
  block:
    - name: Install package
      become: yes
      apt: 
        name: vim
        state: latest

    - name: Copy configuration file
      copy:
        src: 'vimrc'
        dest: "{{ ansible_user_dir }}/.vimrc"
        force: yes
