- name: Install and setup Neovim
  tags: 
    - vim
    - neovim
  block:
    - name: Add NeoVim PPA
      become: yes
      apt_repository: 
        repo: ppa:neovim-ppa/stable
        state: present
        update_cache: yes
        validate_certs: no

    - name: Install packages
      become: yes
      apt: 
        name: "{{ item }}"
        state: latest
      with_items:
        - neovim
        - python3-dev
        - python3-pip
        - python3-neovim

    - name: Copy configuration file
      copy:
        src: 'vimrc'
        dest: "{{ ansible_user_dir }}/.vimrc"
        force: yes
