- name: Preparing installation of Virtualbox
  tags: virtualbox
  become: yes
  block:
    - name: Add Virtualbox repository key
      apt_key:
        url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
        state: present

    - name: Add Virtualbox repository
      apt_repository:
        repo: "https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
        state: present

    - name: Install Virtualbox
      apt:
        update_cache: yes
        name: "virtualbox-{{ virtualbox_version }}"
        state: latest
        autoclean: yes
