- name: Preparing installation of  Virtualbox
  tags:
    - dev
    - virtualbox
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags:
        - dev
        - virtualbox
  vars:
    package:
      name: Virtualbox
      url: "{{ virtualbox_url }}"

