- name: Download and install VSCode
  tags: 
    - dev
    - vscode
  block:
  - name: Download and install package
    become: yes
    apt:
      deb: "{{ vscode_url }}"

  - name: Install sync extenstion
    command: "code --install-extension shan.code-settings-sync"
