- name: Download and install Telegram
  tags: telegram
  block:
  - name: Download package
    get_url:
      url: "{{ telegram_url }}"
      dest: "{{ telegram_dest }}"
    check_mode: no

  - name: Extract package
    unarchive:
      src: "{{ telegram_dest }}"
      dest: "~/"

  - name: Rename application folder
    command: "mv ~/Telegram*/ ~/telegram"

  - name: Create application laucher
    become: yes
    shell: echo -e '[Desktop Entry]\n Version=1.0\n Exec=~/telegram/Telegram\n Icon=Telegram\n Type=Application\n Categories=Application;Network;' | tee ~/.local/share/applications/telegram.desktop

  - name: Remove package
    file:
      path: "{{ telegram_dest }}"
      state: absent
    check_mode: no

- name: Install Discord
  tags: discord
  include_role: 
    name: common
    tasks_from: download_and_install_apt_package
  vars:
    package:
      name: Discord
      tags: discord
      url: "{{ discord_url }}"

