- name: Download and install Telegram
  tags: 
    - comm
    - telegram
  block:
  - name: Download package
    get_url:
      url: "{{ telegram_url }}"
      dest: "{{ telegram_dest }}"
    check_mode: no

  - name: Extract package
    unarchive:
      src: "{{ telegram_dest }}"
      dest: "{{ ansible_user_dir }}"

  - name: Rename application folder
    command: "mv {{ ansible_user_dir }}/Telegram/ {{ ansible_user_dir }}/telegram/"

  - name: Create application laucher
    shell: echo -e '[Desktop Entry]\n Version=1.0\n Exec=~/telegram/Telegram\n Icon=Telegram\n Type=Application\n Categories=Application;Network;' | tee ~/.local/share/applications/telegram.desktop

  - name: Remove package
    file:
      path: "{{ telegram_dest }}"
      state: absent
    check_mode: no

- name: Install Discord
  tags: 
    - comm
    - discord
  include_role: 
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags: 
        - comm
        - discord
  vars:
    package:
      name: Discord
      url: "{{ discord_url }}"

- name: Install Zoom
  tags:
    - comm
    - zoom
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags:
        - comm
        - zoom
  vars:
    package:
      name: Zoom
      url: "{{ zoom_url }}"

