    # Last update 210203.1610

# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1) 
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)" 

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Load custom aliases
if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

# Load custom environment variables
if [ -f ~/.bash_exports ]; then
	source ~/.bash_exports
fi

# enable programmable completion features (you don't need to enable 
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile 
# sources /etc/bash.bashrc). 
if ! shopt -oq posix; then 
if [ -f /usr/share/bash-completion/bash_completion ]; then 
. /usr/share/bash-completion/bash_completion 
elif [ -f /etc/bash_completion ]; then 
. /etc/bash_completion 
fi 
fi 

if [ -z "$STARTED_SCREEN" ] && [ -n "$SSH_TTY" ]; then 
case $- in 
*i*) 
STARTED_SCREEN=1; export STARTED_SCREEN 
mkdir -p -- "$HOME/lib/screen-logs" 
screen -RR -S sid || 
echo >&2 "Screen failed! continuing with normal bash startup" 
esac 
fi 
