# Last update:
# 20240326,1743 - Sidney de Moraes

alias ls='ls --group-directories --color'
alias lsa='ls -A'
alias lsd='ls -d */'
alias ll='ls -lh'
alias llt='ll --sort=time'
alias lls='ll --sort=size'
alias lle='ll --sort=extension'
alias lld='ll -d */'
alias la='ll -A'
alias lat='la --sort=time'
alias las='la --sort=size'
alias lae='la --sort=extension'
alias lad='la -d */'
alias less='less -R'
alias grep=grep -I --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}

function dockerps(){
  (which docker) &> /dev/null && \
  docker ps | awk 'NR==2 {print $1}' | xargs -r docker inspect -f '{{ .State.Pid }} {{ .Config.Hostname }} {{ .Name }}'
}

(which tmux && type tmux) &> /dev/null && alias tmux='tmux -uS /tmp/shareds'
(which tmate && type tmate) &> /dev/null && alias tmate='tmate -uS /tmp/tmate.sock'

# alias resetwifi='sudo dhclient -r wlan0 && sudo dhclient wlan0'
# alias resetnet='sudo dhclient -r eth0 && sudo dhclient eth0'
# alias brightness='xandr --output HDMI1 --brightness '

alias vpnon='nordvpn set killswitch off && nordvpn c Brazil && nordvpn set killswitch on'
alias vpnoff='nordvpn set killswitch off && nordvpn d'
