- name: "Preparing installation of {{ package.name }}"
  block:
    - name: "Get latest release from {{ package.name }}"
      uri:
        url: "{{ github_api_first_part }}/{{ package.repo }}/{{ github_api_last_part }}"
        return_content: yes
        body_format: json
      register: latest

    - name: Print variable for debugging purposes
      debug:
        var: latest
        verbosity: 1

    - name: "Install {{ package.name }} package"
      loop: "{{ latest.json.assets }}"
      when: "{{ '.deb' in item.name and 'arm64' not in item.name and 'armv' not in item.name }}"
      #when: "{{ item.name | regex_search('.*(?<!amr64)(?<!armv7l)\\.deb', ignorecase=True) }}"
      become: yes
      apt:
        deb: "{{ item.browser_download_url }}"

  ignore_errors: yes


