- name: "Preparing installation of {{ package.name }}"
  become: yes
  block:
    - name: "Add APT key for {{ package.name }} Repository"
      apt_key:
        id: "{{ package.key_id }}"
        url: "{{ package.key_url }}"
        state: "{{ package.key_state | default('present') }}"
      when: package.key_id is defined and package.key_url is defined

    - name: "Add {{ package.name }} Repository"
      apt_repository: 
        repo: "{{ package.apt_repo }}"
        state: present
        validate_certs: no
      when: package.apt_repo is defined

    - name: Download and install package
      apt:
        update_cache: yes
        name: "{{ package.id }}"
        state: "{{ package.state | default('latest') }}"
