- name: Install Teams4Linux
  tags: teams
  include_role:
    name: common
    tasks_from: download_and_install_apt_package
  vars:
    package:
      name: Teams4Linux
      tags: teams
      url: "{{ teams4linux_url }}"

