- name: Install Team Viewer
  tags: teamviewer
  include_role: 
    name: common
    tasks_from: download_and_install_apt_package
    apply:
      tags: teamviewer
  vars:
    package:
      name: Team Viewer
      url: "{{ teamviewer_url }}"
